name: fms
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #router
  flutter_modular: ^6.3.2
  # state
  bloc: ^8.1.1
  #network
  dio: ^5.3.4
  #database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  #common
  path_provider: ^2.0.15
  equatable: ^2.0.5
  intl: ^0.19.0
  intl_utils: ^2.8.5
  image: ^4.1.3
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.10+1
  #service
  permission_handler: ^10.4.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  #widget
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  table_calendar: ^3.1.0
  stop_watch_timer: ^3.1.1
  camerawesome: ^2.0.1-dev.1

  
  #tool
  flutter_flavor: ^3.1.1
  change_app_package_name: ^1.1.0
  #flutter pub run change_app_package_name:main com.new.package.name
  
  google_maps_flutter: ^2.5.3
  flutter_bloc: ^8.1.3

  #animation
  animate_do: ^3.3.4
  random_string: ^2.3.1
  

  
  
dependency_overrides:
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/fonts/AppIcon.ttf
# flutter pub run intl_utils:generate
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: L # Optional. Sets the name for the generated localization class. Default: S
  arb_dir: lib/l10n
  main_locale: vi # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  

